### ISSUE TITLE
New config option to not comment on PRs at all

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#168]
Hey! We're using (and loving) packit in
    [osbuild](https://github.com/osbuild/osbuild). We tend to have lots of
    back-and-forth on pull requests, force pushing regularly. packit's
    notifications add a lot of clutter, both to the discussion and to
    notifications.
    
    Honestly, I'd prefer *only* having the status and no comments at all.

_Originally posted by @larskarlitski in https://github.com/packit-service/packit-service/issues/4#issuecomment-527021083_

**Comment by TomasTomecek** [comment]
Related to #1

**Comment by lachmanfrantisek** [comment]
We are still waiting for the logs.

**Comment by TomasTomecek** [comment]
proposal: introduce a new config option:
```
pull_request_comment_successful_build
```

it would default to true and people would be able to set it to false

true = comment with Congratulations
false = don't comment

**Comment by csomh** [comment]
How about:

```yaml
comment:
    pull_request:
        successful_build: false
```

To allow adding more in the future.

**Comment by TomasTomecek** [comment]
I mean, I'd love to see something like:
```yaml
notifications:
    comment:
        pull_request:
            successful_build: false
```
but yours have only 3 lines, so let's do yours
