### ISSUE TITLE
Allow `downstream_package_name` to be specified per-job

### ISSUE THREAD

**Issue by sgallagher** [packit-service/packit-service#418]
Some packages have different names on different Fedora/EPEL releases (for example, a newer version of a library on EPEL 7 might be named in the form `packagename$version` while in Fedora it is just `packagename`.

It should be possible to do the following:
```
specfile_path: libmodulemd.spec
upstream_package_name: libmodulemd
downstream_package_name: libmodulemd
upstream_tag_template: libmodulemd-{version}
current_version_command:
  - ./.packit_version.sh

synced_files:
  - .packit.yml
  - .make_packit_specfile.sh
  - libmodulemd.spec

actions:
    post-upstream-clone: ./.make_packit_specfile.sh

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets: fedora-all

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: fedora-all

- job: propose_downstream
  trigger: release
  metadata:
    dist-git-branch: epel-7
    downstream_package_name: libmodulemd2
```
