### ISSUE TITLE
[propose_downstream job] Allow to specify more branches

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#59]
Looking at [this PR](https://github.com/packit-service/ogr/pull/135/files) I'm wondering whether it would be more user-friendly if there was a way how to specify all branches in one job, i.e.

```yaml
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - master
    - f30
    - f29
```
instead of
```yaml
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: master
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: f30
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: f29
```
