### ISSUE TITLE
Allow multiple triggers for a job

### ISSUE THREAD

**Issue by bocekm** [packit-service/packit-service#647]
Currently I can specify only one trigger for a job:
```
- job: copr_build
  trigger: commit
  metadata:
    branch: build-branch
```
To avoid duplicate code in the packit config - specifying two jobs for basically the same - allow specifying multiple triggers. E.g.
```
- job: copr_build
  triggers:
    - commit
    - pull_request
  metadata:
    branch: build-branch
```
